name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Before submitting an issue, please check the following
      options:
        - label: I have searched for similar issues (both open and closed) and cannot find a duplicate
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/WayneKeenan/ClintonCAT/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Clearly describe the bug you've encountered.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Decribe what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: ClintonCAT version
      description: |
        You can find this in the manifest.json file.
      placeholder: e.g. 1.0
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: Please complete the following information
      value: |
        - OS:
        - Browser: 

        <!--
        Example:
        - OS: Android 13
        - Browser: Firefox 134.0.2 (64 bit)
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Screen recordings are especially useful!
    validations:
      required: false
